### ISSUE TITLE
Consider use of async/await ?.?

### ISSUE THREAD

**Issue by airondumael** [anyTV/anytv-node-boilerplate#5]
I'm suggesting that we consider use of es7 async/await. It is not yet natively supported but we are using babel. 

This can possibly makes our controllers more readable. 
- It will eliminate declarations of functions in our controllers that are only use to make our codes sync. 
- It will make as able to use the old try catch for error handling compare to always having an if (err) statement. 
- It is easier to read as it looks more natural.

See code sample below. 

*it is just a draft and i'm not sure if it will run.

**Current**
```javascript
exports.get_user = (req, res, next) => {

    function start () {
        mysql.use('my_db')
            .query(
                'SELECT * FROM users WHERE user_id = ? LIMIT 1;',
                [req.params.id],
                send_response
            )
            .end();
    }

    function send_response (err, result, args, last_query) {
        if (err) {
            winston.error('Error in selecting users', last_query);
            return next(err);
        }

        if (!result.length) {
            return res.warn(404, {message: 'User not found'});
        }

        res.send(result[0]);
    }

    start();
};
```

**Async/Await**
```javascript
exports.get_user = async (req, res, next) => {
    let id = req.params.id;
    let user = {};

    try {
        user = await UserModel.get_user_by_id(id);
    } catch (err) {
        winston.error('Error in selecting users');

        return next(err)
    }

    if (!user.length) {
        return res.warn(404, {message: 'User not found'});
    }

    res.send(user[0]);
};

// somewhere in models directory
UserModel = {
    get_user_by_id: (id) => {
        return new Promise((resolve, reject) => {
            mysql.use('my_db')
                .query(
                    'SELECT * FROM users WHERE user_id = ? LIMIT 1;',
                    [id],
                    (err, result) => {
                        if (err) {
                            throw new Error(err)
                        }

                        resolve(result)
                    }
                )
                .end();
        })
    }
}

// doing multiple async
async function () {
    var data = await Promise.all([asyncFunc(), asyncFunc(), asyncFunc()]);
   // do things on data
}

``` 

*I'm not sure if this is good.

**Comment by ravenjohn** [comment]
you're suggesting something that you're not sure if good :laughing:

**Comment by ravenjohn** [comment]
* yes, it looks natural but
* es7 right now is just a bunch of proposals while es6 is already a standard;
* this repo is not using babel;
* if you look closely, user model is too deep;
* you still have `if (err) {`;
* try catch does not look good, imho.

**Comment by airondumael** [comment]
I'm not sure if it's good because other parts of the code might get bigger because we have to covert them to promises.

Sorry, did not check if this is using babel. I just thought we will be using it base on the es6 discussion few weeks back.

Yes user model is deep but maybe it can be improved and it is only 1 level deeper. 

We can lessen the if (err) part by creating a generic callback and reusing it for our callback base functions to support es6.

About es7 just being a bunch of proposals, if we will be using babel in the future (because we are not yet using it) it does not matter that match as the codes will be transpiled to es5 and will still work IMO it's like SASS/LESS for css. It makes writing code easier without waiting for the engines to support it.

**Comment by airondumael** [comment]
we are not using babel :cry:
