### ISSUE TITLE
Suggest to change user tables to InnoDB

### ISSUE THREAD

**Issue by pandafox** [anyTV/anytv-node-boilerplate#6]
I think it is important that we discuss the design of the DBs. Especially other projects are using this as the base, we should consider and weight the consequences of different DB engines at our disposal. In general, relationship DB design should be normalized and FK should be created to ensure that join queries have good performance.

http://stackoverflow.com/questions/12614541/whats-the-difference-between-myisam-and-innodb
http://dba.stackexchange.com/questions/17431/which-is-faster-innodb-or-myisam
http://stackoverflow.com/questions/20148/myisam-versus-innodb

Assuming most sites will be User-centred (ie: storing user data), additional benefit are:

1. user data can be more easily managed with FK, such as cascade update/delete etc., (referential integrity)
2. Relationship between data can be quickly realized by DB schema
3. DB query can use it for optimizing queries
4. Avoid problems when designing the schema (I have seem some table schema that are meant to store the same data to have different column width/type, while the DB would allow you to put in data, it creates unnecessary data issue that could have been avoided all together on design time.)
5. InnoDB also supports transaction, which is crucial when dealing with sensitive data such as money and user information. 

Thoughts?

**Comment by ravenjohn** [comment]
Hi @pandafox, the user table is really just a sample. The engine used was not thought carefully. I agree that changing it to InnoDB will make it better.

**Comment by ravenjohn** [comment]
Fixed https://github.com/anyTV/anytv-node-boilerplate/commit/9f0f458c833eef60a9f27ef7ac2fdabf12b20653
